'use client'

import { useState } from 'react'
import { useLocation } from '@/context/LocationContext'

export default function FarmReportButton() {
  const { location } = useLocation()
  const [loading, setLoading] = useState(false)

  async function downloadReport() {
    if (!location) return
    setLoading(true)
    try {
      const [weatherResponse, mandiResponse, statsResponse] = await Promise.all([
        fetch(`/api/weather?lat=${location.lat}&lon=${location.lon}&type=current`),
        fetch('/api/mandi'),
        fetch(`/api/farm-stats?lat=${location.lat}&lon=${location.lon}`),
      ])
      const [weather, mandi, stats] = await Promise.all([
        weatherResponse.json(), mandiResponse.json(), statsResponse.json(),
      ])
      const prices = Array.isArray(mandi)
        ? mandi.map((item: { crop: string; price: string; market: string }) => `• ${item.crop}: ${item.price}/quintal (${item.market})`).join('\n')
        : 'Mandi data is temporarily unavailable.'
      const report = `KHETSATHI AI — FARM ACTION REPORT\nGenerated: ${new Date().toLocaleString('en-IN')}\n\nLOCATION\n${location.display}\n\nLIVE WEATHER\n${Math.round(weather.main?.temp ?? 0)}°C · Humidity ${weather.main?.humidity ?? '—'}% · ${weather.weather?.[0]?.description ?? 'Unavailable'}\n\nFIELD STATUS\nCrop health: ${stats.cropHealth ?? '—'}\nIrrigation: ${stats.irrigationNeeded ? 'Recommended soon' : 'Conditions stable'}\nWater estimate: ${stats.waterUsed ?? '—'}\n\nLIVE MANDI PRICES\n${prices}\n\nGenerated by KhetSathi AI — Smart farming for Bharat.`
      const file = new Blob([report], { type: 'text/plain;charset=utf-8' })
      const url = URL.createObjectURL(file)
      const anchor = document.createElement('a')
      anchor.href = url
      anchor.download = `khetsathi-farm-report-${new Date().toISOString().slice(0, 10)}.txt`
      anchor.click()
      URL.revokeObjectURL(url)
    } finally {
      setLoading(false)
    }
  }

  return (
    <button
      onClick={downloadReport}
      disabled={!location || loading}
      className="text-xs font-semibold px-3 py-2 rounded-xl transition-all disabled:opacity-50"
      style={{ color: '#dcfce7', background: 'rgba(74,222,128,0.12)', border: '1px solid rgba(74,222,128,0.28)' }}
    >
      {loading ? 'Preparing report…' : '⇩ Download Farm Report'}
    </button>
  )
}
